site_name: raft
theme: readthedocs
pages:
- raft: index.md
- package raft:
  - Package: "raft--index.md"
  - type _Role: "raft-_Role.md"
  - class Server: "raft-Server.md"
  - class _LeaderRole: "raft-_LeaderRole.md"
  - class _FollowerRole: "raft-_FollowerRole.md"
  - class _CandidateRole: "raft-_CandidateRole.md"
- package builtin:
  - Package: "builtin--index.md"
  - interface ReadSeq: "builtin-ReadSeq.md"
  - interface ReadElement: "builtin-ReadElement.md"
  - primitive F32: "builtin-F32.md"
  - primitive F64: "builtin-F64.md"
  - type Float: "builtin-Float.md"
  - class String: "builtin-String.md"
  - class StringBytes: "builtin-StringBytes.md"
  - class StringRunes: "builtin-StringRunes.md"
  - primitive _UTF32Encoder: "builtin-_UTF32Encoder.md"
  - primitive None: "builtin-None.md"
  - primitive _ToString: "builtin-_ToString.md"
  - interface Iterator: "builtin-Iterator.md"
  - primitive Platform: "builtin-Platform.md"
  - interface Stringable: "builtin-Stringable.md"
  - interface Any: "builtin-Any.md"
  - type AsioEventID: "builtin-AsioEventID.md"
  - interface AsioEventNotify: "builtin-AsioEventNotify.md"
  - primitive AsioEvent: "builtin-AsioEvent.md"
  - class Array: "builtin-Array.md"
  - class ArrayKeys: "builtin-ArrayKeys.md"
  - class ArrayValues: "builtin-ArrayValues.md"
  - class ArrayPairs: "builtin-ArrayPairs.md"
  - interface SourceLoc: "builtin-SourceLoc.md"
  - type ByteSeq: "builtin-ByteSeq.md"
  - interface ByteSeqIter: "builtin-ByteSeqIter.md"
  - interface OutStream: "builtin-OutStream.md"
  - actor StdStream: "builtin-StdStream.md"
  - primitive AmbientAuth: "builtin-AmbientAuth.md"
  - primitive DoNotOptimise: "builtin-DoNotOptimise.md"
  - struct Pointer: "builtin-Pointer.md"
  - struct MaybePointer: "builtin-MaybePointer.md"
  - primitive I8: "builtin-I8.md"
  - primitive I16: "builtin-I16.md"
  - primitive I32: "builtin-I32.md"
  - primitive I64: "builtin-I64.md"
  - primitive ILong: "builtin-ILong.md"
  - primitive ISize: "builtin-ISize.md"
  - primitive I128: "builtin-I128.md"
  - type Signed: "builtin-Signed.md"
  - primitive U8: "builtin-U8.md"
  - primitive U16: "builtin-U16.md"
  - primitive U32: "builtin-U32.md"
  - primitive U64: "builtin-U64.md"
  - primitive ULong: "builtin-ULong.md"
  - primitive USize: "builtin-USize.md"
  - primitive U128: "builtin-U128.md"
  - type Unsigned: "builtin-Unsigned.md"
  - interface StdinNotify: "builtin-StdinNotify.md"
  - interface DisposableActor: "builtin-DisposableActor.md"
  - actor Stdin: "builtin-Stdin.md"
  - primitive Less: "builtin-Less.md"
  - primitive Equal: "builtin-Equal.md"
  - primitive Greater: "builtin-Greater.md"
  - type Compare: "builtin-Compare.md"
  - interface HasEq: "builtin-HasEq.md"
  - interface Equatable: "builtin-Equatable.md"
  - interface Comparable: "builtin-Comparable.md"
  - trait _ArithmeticConvertible: "builtin-_ArithmeticConvertible.md"
  - trait Real: "builtin-Real.md"
  - trait Integer: "builtin-Integer.md"
  - trait _SignedInteger: "builtin-_SignedInteger.md"
  - trait _UnsignedInteger: "builtin-_UnsignedInteger.md"
  - trait FloatingPoint: "builtin-FloatingPoint.md"
  - type Number: "builtin-Number.md"
  - type Int: "builtin-Int.md"
  - primitive Bool: "builtin-Bool.md"
  - class Env: "builtin-Env.md"
  - interface Seq: "builtin-Seq.md"
- package collections:
  - Package: "collections--index.md"
  - interface Flag: "collections-Flag.md"
  - class Flags: "collections-Flags.md"
  - primitive Sort: "collections-Sort.md"
  - class RingBuffer: "collections-RingBuffer.md"
  - interface Hashable: "collections-Hashable.md"
  - interface HashFunction: "collections-HashFunction.md"
  - primitive HashEq: "collections-HashEq.md"
  - primitive HashIs: "collections-HashIs.md"
  - primitive HashByteSeq: "collections-HashByteSeq.md"
  - type Set: "collections-Set.md"
  - type SetIs: "collections-SetIs.md"
  - class HashSet: "collections-HashSet.md"
  - class SetValues: "collections-SetValues.md"
  - class List: "collections-List.md"
  - class ListNodes: "collections-ListNodes.md"
  - class ListValues: "collections-ListValues.md"
  - class ListNode: "collections-ListNode.md"
  - primitive _MapEmpty: "collections-_MapEmpty.md"
  - primitive _MapDeleted: "collections-_MapDeleted.md"
  - type Map: "collections-Map.md"
  - type MapIs: "collections-MapIs.md"
  - class HashMap: "collections-HashMap.md"
  - class MapKeys: "collections-MapKeys.md"
  - class MapValues: "collections-MapValues.md"
  - class MapPairs: "collections-MapPairs.md"
  - class Reverse: "collections-Reverse.md"
  - class Range: "collections-Range.md"
- package ponytest:
  - Package: "ponytest--index.md"
  - trait TestList: "ponytest-TestList.md"
  - interface ITest: "ponytest-ITest.md"
  - class TestHelper: "ponytest-TestHelper.md"
  - actor PonyTest: "ponytest-PonyTest.md"
  - trait UnitTest: "ponytest-UnitTest.md"
  - primitive _Color: "ponytest-_Color.md"
  - trait _Group: "ponytest-_Group.md"
  - actor _ExclusiveGroup: "ponytest-_ExclusiveGroup.md"
  - actor _SimultaneousGroup: "ponytest-_SimultaneousGroup.md"
- package time:
  - Package: "time--index.md"
  - interface TimerNotify: "time-TimerNotify.md"
  - primitive Nanos: "time-Nanos.md"
  - class _TimingWheel: "time-_TimingWheel.md"
  - class Timer: "time-Timer.md"
  - actor Timers: "time-Timers.md"
  - class Date: "time-Date.md"
  - type _Clock: "time-_Clock.md"
  - primitive _ClockRealtime: "time-_ClockRealtime.md"
  - primitive _ClockMonotonic: "time-_ClockMonotonic.md"
  - primitive Time: "time-Time.md"
